<?php

$type = 'गाउँ';
        return [
        'app_name_yojana' => 'yojana',
        'app_name_pis' => 'pis',
        'app_name_nagadi' => 'nagadi',
        'app_name_malpot' => 'malpot',
        'app_name_byabasaye' => 'byabasaye',
        'wada_stariya_id' => 26,
        'nagar_stariya_id' => 25,
        'SITE_TYPE' => $type.'पालिका',
        'SITE_NAME' => 'चुलाचुली  ' . $type . 'पालिका',
        'SITE_ADDRESS' => 'चुलाचुली',
        'SITE_SUB_TYPE' => $type.' कार्यपालिकाको कार्यालय',
        'SITE_SUB_TYPE_WARD' =>' नं वडा कार्यालय',
        'FULL_ADDRESS' => 'प्रदेश नं १, नेपाल',
        'SITE_DISTRICT' => 'ईलाम',
        'SITE_NAME_ENGLISH' => 'Chulachuli Rural Municipality',
        // samiti gathan useful id :)
        'TOLE_SAMYOJAK_ID' => 51,
        'TOLE_SADASYA_ID' => 52,
        'TOLE_ADAKSHYA_ID' => 47,
        'TOLE_UPAADAKSHYA_ID' => 48,
        'TOLE_SACHIB_ID' => 50,
        'TOLE_KOSADAKSHYA_ID' => 49,
        'TOTAL_WARDS'=> 6,
        'BIGGA'=> 'रोपनी',
        'KATTHA'=> 'आना',
        'DHUR'=> 'पैसा',
        'KANUA'=> 'दाम',
        'BIGGA_SMALL'=> 'रो',
        'KATTHA_SMALL'=> 'आ',
        'DHUR_SMALL'=> 'पै',
        'KANUA_SMALL'=> 'दा',
        'LAND'=> 'hill',
        'GENDER' => ['female' => 'महिला', 'male' => 'पुरुष', 'other' => 'अन्य'],
        'SUPERADMIN_ID' => 2,
        'SUPERADMIN_ROLE_ID' => 1
    ];
